version: '3'

services:
  # Service API
  api:
    build:
      context: ./back
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=gamerchallenge-database
      - DB_PORT=5432
      - DB_USER=gamerchallenge
      - DB_PASSWORD=gamerchallenge
      - DB_NAME=gamerchallenge
      - PG_URL=postgres://gamerchallenge:gamerchallenge@gamerchallenge-database:5432/gamerchallenge  # Ajouter cette ligne
    depends_on:
      - db
    container_name: gamerchallenge-api
    networks:
      - gamerchallenge-network

  # Service Client (Frontend)
  client:
    build:
      context: ./front
      dockerfile: Dockerfile.cli
    ports:
      - "4173:4173"
    depends_on:
      - api
    container_name: gamerchallenge-cli
    networks:
      - gamerchallenge-network

  # Service Base de Données (PostgreSQL)
  db:
    image: postgres:latest
    container_name: gamerchallenge-database
    environment:
      - POSTGRES_USER=gamerchallenge
      - POSTGRES_PASSWORD=gamerchallenge
      - POSTGRES_DB=gamerchallenge
    ports:
      - "5433:5432"
    volumes:
      - pg-gamerchallenge:/var/lib/postgresql/data
    networks:
      - gamerchallenge-network

# Déclaration du volume pour la persistance des données de la base de données
volumes:
  pg-gamerchallenge:

# Déclaration du réseau pour que tous les services puissent se connecter entre eux
networks:
  gamerchallenge-network:
    driver: bridge
