version: '3'

services:
  # Service API
  api:
    build:
      context: ./back
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: gamerchallenge-api

  # Service Client (Frontend)
  client:
    build:
      context: ./front
      dockerfile: Dockerfile.cli
    ports:
      - "4173:4173"
    depends_on:
      - api
    container_name: gamerchallenge-cli

  # Service Base de Données (PostgreSQL)
  db:
    image: postgres:latest
    container_name: gamerchallenge-database
    environment:
      - POSTGRES_USER=gamerchallenge
      - POSTGRES_PASSWORD=gamerchallenge
      - POSTGRES_DB=gamerchallenge
    ports:
      - "5432:5432"
    volumes:
      - pg-gamerchallenge:/var/lib/postgresql/data

# Déclaration du volume pour la persistance des données de la base de données
volumes:
  pg-gamerchallenge:
