# ./back/Dockerfile.api
FROM node:lts-alpine

WORKDIR .

# Installation des dépendances globales nécessaires
RUN npm install -g sequelize-cli

# Copie des fichiers de dépendances
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie du reste du code source
COPY . .

# Exécution des migrations avant de démarrer l'API
CMD ["sh", "-c", "npm run db:reset && npm start"]

# Exposition du port
EXPOSE 3000