# ./front/Dockerfile.cli
FROM node:18-alpine

WORKDIR /app

# copy dependencies
COPY package*.json ./

# Installation dependencies
RUN npm install

# copy source code
COPY . .

# application Build
RUN npm run build

# Port

EXPOSE 4173

# Starting code ( adapt with your configuation)
CMD ["npm", "run", "preview", "--host"]